TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devPMD90.db
DB_INSTALLS += $(TOP)/PMD90Sup/devPMD90.proto

#=======================================
include $(TOP)/configure/RULES
